name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always
  target: x86_64-unknown-linux-musl

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install musl
      run: sudo apt-get update && sudo apt-get install -y musl musl-tools
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ env.target }}
        default: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ env.target }}
    - name: Move binary
      run: mv target/${{ env.target }}/release/sgmm sgmm-${{ env.target }}
    - name: Strip binary
      run: strip sgmm-${{ env.target }}
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: sgmm-${{ env.target }}
        path: sgmm-${{ env.target }}
    - name: Release binary
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sgmm-${{ env.target }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
